feat: refactor Makefiles to standardize pre-deployment tasks and add crontab support for home automation

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -28,11 +28,13 @@ read -r -a project_list <<<"$PROJECTS"
 
 for project in "${project_list[@]}"; do
   echo "Deploying ${project}"
-  # You'd think remove orphans and force recreate would work to bring things up in a great state,
-  # but it seems to have problems with the files stack. Not sure why yet.
-  make --no-print-directory "${project}-pull"
-  make --no-print-directory "${project}-down"
-  make --no-print-directory "${project}-deploy"
+  if [ -d "$project" ]; then
+    (cd "$project" && make --no-print-directory pull)
+    (cd "$project" && make --no-print-directory deploy)
+  else
+    echo "Project directory $project not found"
+    exit 1
+  fi
 done
 
 make --no-print-directory docker-prune
